name: CI Checks
permissions:
  contents: read

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  lint_typecheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: current
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn typecheck
    - run: yarn build
